MusicMVC/Controllers/ArtistController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicMVC.Data;
using MusicMVC.Data.Entities;
using MusicMVC.ViewModels;
using System.Linq;

namespace MusicMVC.Controllers
{
    [Authorize(Roles = "Manager, Admin")]
    public class ArtistController : Controller
    {
        private readonly MusicDbContext _context;
        public ArtistController(MusicDbContext context) 
        {
            _context = context;
        }

        // GET: ArtistController/Create
        public ActionResult Create()
        {
            TempData.Keep();
            return View();
        }

        // POST: ArtistController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ArtistViewModel artistVM)
        {
            try
            {
                var countArtist = await _context.Artists.CountAsync();
                var newArtist = new Artist
                {
                    Name = artistVM.Name.Trim(),
                    Nickname = artistVM.Nickname?.Trim(),
                    Gender = artistVM.Gender,
                    DateOfBirth = artistVM.DateOfBirth,
                    MusicCount = 0,
                    Position = countArtist + 1,
                };
                _context.Artists.Add(newArtist);
                await _context.SaveChangesAsync();


                //ViewBag.Message = "Thêm Thành Công";
                TempData["Message"] = "Thêm Thành Công";
                //=== Lưu thành công thì quay về cho tạo tiếp ===//
                return RedirectToAction(nameof(Create));
            }
            catch
            {
                TempData["Message"] = "Thêm Thất Bại";
                //=== Không thành công thì kiểm tra lại dữ liệu ===//
                return View(nameof(Create), artistVM);
                
            }
        }

        // GET: ArtistController/Edit/5
        public async Task<ActionResult> Edit(Guid idArtist)
        {
            // thêm await thì nhớ thêm async và task
            var artistVM = await _context.Artists
                .Where(a => a.Id.Equals(idArtist)) //trả về kiểu nguyên thủy equals
                .Select(a => new ArtistViewModel
                {
                    Id = a.Id,
                    Name = a.Name,
                    Nickname= a.Nickname,
                    Gender = a.Gender,
                    DateOfBirth = a.DateOfBirth,
                    //Position = a.Position,
                })
                .SingleOrDefaultAsync();
            if (artistVM == null) return BadRequest();

            return View(nameof(Create), artistVM);
        }

        // POST: ArtistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Artist artistVM)
        {
            try
            {
                var artist = await _context.Artists.FindAsync(artistVM.Id);
                if (artist ==null) return BadRequest();

                artist.Name = artistVM.Name.Trim();
                artist.Nickname = artistVM.Nickname.Trim();
                artist.Gender = artistVM.Gender;
                artist.DateOfBirth = artistVM.DateOfBirth;

                await _context.SaveChangesAsync();


                //ViewBag.Message = "Thêm Thành Công";
                TempData["Message"] = "Sửa Thành Công";
                //=== Lưu thành công thì quay về cho tạo tiếp ===//
                return RedirectToAction(nameof(Create));
            }
            catch
            {
                TempData["Message"] = "Sửa Thất Bại";
                //=== Không thành công thì kiểm tra lại dữ liệu ===//
                return View(nameof(Create), artistVM);
            }
        }

        // GET: ArtistController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ArtistController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MusicMVC/Controllers/MusicController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using MusicMVC.Commons;
using MusicMVC.Data;
using MusicMVC.Data.Entities;
using MusicMVC.Enums;
using MusicMVC.ViewComponents;
using MusicMVC.ViewModels;


namespace MusicMVC.Controllers
{
    [Authorize(Roles = "Manager, Editor")]
    public class MusicController : BaseController
    {
        private readonly IWebHostEnvironment _environment;
        private readonly MusicDbContext _context;
        public MusicController(MusicDbContext context, IWebHostEnvironment environment)
            : base(environment, context)
        {
            _context = context;
            _environment = environment;
        }
        public async Task<IActionResult> Create()
        {

            ViewBag.Artists = await GetArtistSelectList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MusicViewModel musicVM)
        {
            try
            {
                var media = await SaveMedia(musicVM.FileMusic);

                var countMusic = await _context.Musics.CountAsync();
                var newMusic = new Data.Entities.Music
                {
                    Name = musicVM.Name.Trim(),
                    Lyrics = musicVM.Lyrics.Trim(),
                    Price = musicVM.Price,
                    PriceDiscounted = musicVM.PriceDiscounted,
                    ArtistId = musicVM.ArtistId,
                    //FileName = fileGuidName,
                    MediumId = media != null ? media.Id : null,
                    Position = countMusic + 1,

                };
                //newMusic.FileName = musicVM.Get(newMusic);

                _context.Musics.Add(newMusic);
                await UpdateMusicCountByArtist(musicVM.ArtistId, 1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Create));

            }
            catch
            {
                ViewBag.Artists = await GetArtistSelectList();
                return View(musicVM);
            }
        }

        // GET: MusicController/Edit/5
        public async Task<ActionResult> Edit(Guid idMusic)
        {
            // thêm await thì nhớ thêm async và task
            //var music = await _context.Musics.FindAsync(idMusic);
            var music = await _context.Musics
                .Where(m => m.Id.Equals(idMusic))
                .Include(m => m.Medium)
                .SingleOrDefaultAsync();
            if (music == null) return BadRequest();
            var musicVM = new MusicViewModel
            {
                Id = music.Id,
                Name = music.Name,
                Lyrics = music.Lyrics,
                Price = music.Price,
                PriceDiscounted = music.PriceDiscounted,
                ArtistId = music.ArtistId,
                //FileName = music.FileName,
                MusicPath = MusicViewModel.GetMusicPath(music),
            };
            ViewBag.Artists = await GetArtistSelectList();
            //return View("Create", music);
            return View(nameof(Create), musicVM);
        }

        // POST: ArtistController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(MusicViewModel musicVM)
        {
            try
            {
                //_context.Entry(music).State = EntityState.Modified;
                var music = await _context.Musics.FindAsync(musicVM.Id);
                if (music == null) { return BadRequest(); }
                //=== Sửa trường nào thì cập nhật trường đó ===//
                music.Name = musicVM.Name;
                music.Lyrics = musicVM.Lyrics;
                music.Price = musicVM.Price;
                music.PriceDiscounted = musicVM.PriceDiscounted;
                if (musicVM.ArtistId != music.ArtistId)
                {
                    await UpdateMusicCountByArtist(musicVM.ArtistId, 1);
                    await UpdateMusicCountByArtist(musicVM.ArtistId, -1);

                    music.ArtistId = musicVM.ArtistId;
                }
                if (musicVM.FileMusic != null)//
                {
                    //=== Update Media ===//
                    var media = await SaveMedia(musicVM.FileMusic);
                    if (media != null)
                    {
                        music.MediumId = media.Id;
                    }
                }
                await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Create));
            }
            catch
            {
                ViewBag.Artists = await GetArtistSelectList();
                return View(nameof(Create), musicVM);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid idMusic)
        {
            var status = false;
            var message = "Chưa thực thi";
            try
            {
                //var music = await _context.Musics.FindAsync(idMusic);
                //=== Predicate/delgate ===//
                var music = await _context.Musics
                    .Where(m => m.Id.Equals(idMusic))
                    .Include(m => m.Artist)
                    .SingleOrDefaultAsync();
                if (music != null)
                {
                    //=== Step 1: Decreasement Position ===//
                    var currentPosition = music.Position;
                    var listMusic = await _context.Musics
                        .Where(x => x.Position > currentPosition)
                        .ToListAsync();
                    if(listMusic != null && listMusic.Count > 0)
                    {
                        foreach (var item in listMusic)
                        {
                            item.Position -= 1;
                        }
                    }
                    //=== Step 2: Recalculate MusicCount in Artist ===//
                    music.Artist.MusicCount -= 1;

                    //=== Step 3: Remove Music ====//
                    _context.Musics.Remove(music);
                }

                await _context.SaveChangesAsync();
                status = true;
                message = "Thành công";
            }
            catch
            {
                message = "Lỗi thực thi";
            }
            return Json(new {status, message });
        }
        public IActionResult ReloadMusicList(int currentPage = 1)
        {

            return ViewComponent(nameof(MusicList), new { currentPage });
        }
        private async Task<bool> UpdateMusicCountByArtist(Guid idArtist, int valueChanged)
        {
            var isOk = false;

            var artist = await _context.Artists.FindAsync(idArtist);
            if (artist != null)
            {
                artist.MusicCount += valueChanged;
            }
            return isOk;
        }
        private async Task<SelectList> GetArtistSelectList()
        {
            var listArtist = await _context.Artists
                .Select(a => new
                {
                    Id = a.Id,
                    Name = a.Name,
                })
                .ToListAsync();
            return new SelectList(listArtist, "Id", "Name");
        }
        public async Task<IActionResult> ProductList()
        {
            var model = await _context.Musics
                .Include(m => m.Artist)
                .Include(m => m.Medium)
                .OrderBy(m => m.Position)
                .Select(m => new MusicViewModel
                {
                    Id = m.Id,
                    Name = m.Name,
                    Lyrics = m.Lyrics,
                    Position = m.Position,
                    Price = m.Price,
                    PriceDiscounted = m.PriceDiscounted,
                    //MusicPath = Constants.Music_Path + m.Medium.FileName = "." + m.Medium.Extension,
                    MusicPath = MusicViewModel.GetMusicPath(m),
                })
                .ToArrayAsync();

            return View(model);
        }
    }
}

MusicMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MusicMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MusicMVC.styles.css" asp-append-version="true" />
    <link href=" ~/fontawesome-free-6.5.2-web/css/fontawesome.css" rel="stylesheet" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MusicMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Music" asp-action="Create">Music</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Create">Artist</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MusicMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MusicMVC/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
    <meta name="keywords" content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <title>Dashboard sales - Modern Admin - Clean Bootstrap 4 Dashboard HTML Template + Bitcoin Dashboard</title>
    <link rel="apple-touch-icon" href="~/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CQuicksand:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/app-assets/fonts/material-icons/material-icons.css">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/material-vendors.min.css">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/material.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/components.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/material-extended.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/material-colors.css">
    <!-- END: Theme CSS-->
    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/material-vertical-compact-menu.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/colors/material-palette-gradient.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/fonts/mobiriseicons/24px/mobirise/style.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/charts/jquery-jvectormap-2.0.3.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/charts/morris.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/fonts/simple-line-icons/style.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/colors/material-palette-gradient.css">
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <!-- END: Custom CSS-->
    <!-- Boostrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />
    <!-- Font Awesome CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />

</head>
<!-- END: Head-->
<!-- BEGIN: Body-->

<body class="vertical-layout vertical-compact-menu material-vertical-layout material-layout 2-columns   fixed-navbar" data-open="click" data-menu="vertical-compact-menu" data-col="2-columns">

    <!-- BEGIN: Header-->
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-light navbar-shadow navbar-brand-center">
        <div class="navbar-wrapper">
            <partial name="_PartialViewHeader" />
        </div>
    </nav>
    <!-- END: Header-->
    <!-- BEGIN: Main Menu-->

    <div class="main-menu material-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
        <div class="main-menu-content">
            <partial name="_PartialViewMenu" />
        </div>
    </div>

    <!-- END: Main Menu-->
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-header row">
        </div>
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-body">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- END: Content-->
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-border navbar-shadow">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">Copyright &copy; 2019 <a class="text-bold-800 grey darken-2" href="https://1.envato.market/modern_admin" target="_blank">PIXINVENT</a></span><span class="float-md-right d-none d-lg-block">Hand-crafted & Made with<i class="ft-heart pink"></i><span id="scroll-top"></span></span></p>
    </footer>
    <!-- END: Footer-->
    <partial name="_PartialViewScripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
<!-- END: Body-->

</html>

MusicMVC/Views/Shared/_PartialViewScripts.cshtml
    <!-- BEGIN: Vendor JS-->
<script src="~/app-assets/vendors/js/material-vendors.min.js"></script>
<!-- BEGIN Vendor JS-->
<!-- BEGIN: Page Vendor JS-->
<script src="~/app-assets/vendors/js/charts/chart.min.js"></script>
<script src="~/app-assets/vendors/js/charts/raphael-min.js"></script>
<script src="~/app-assets/vendors/js/charts/morris.min.js"></script>
<script src="~/app-assets/vendors/js/charts/jvector/jquery-jvectormap-2.0.3.min.js"></script>
<script src="~/app-assets/vendors/js/charts/jvector/jquery-jvectormap-world-mill.js"></script>
<script src="~/app-assets/data/jvector/visitor-data.js"></script>
<!-- END: Page Vendor JS-->
<!-- BEGIN: Theme JS-->
<script src="~/app-assets/js/core/app-menu.js"></script>
<script src="~/app-assets/js/core/app.js"></script>
<!-- END: Theme JS-->
<!-- BEGIN: Page JS-->
<script src="~/app-assets/js/scripts/pages/material-app.js"></script>
@* <script src="~/app-assets/js/scripts/pages/dashboard-sales.js"></script> *@
<!-- END: Page JS-->